/* ============================================================
					MediTech (versión 1.0)
   ============================================================ */

CREATE DATABASE MediTech;
GO

USE MediTech;
GO

CREATE SCHEMA ADM;
GO
CREATE SCHEMA CLI;
GO
CREATE SCHEMA CAJA;
GO
CREATE SCHEMA CAT;
GO

/* =========================
		CATÁLOGOS
   ========================= */

CREATE TABLE CAT.TBL_ESTADOS
(
    ID_ESTADO      INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ESTADOS PRIMARY KEY,
    DESC_ESTADO    VARCHAR(80) NOT NULL,
    FECHA_REGISTRO DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO

CREATE UNIQUE INDEX UX_ESTADOS_DESC ON CAT.TBL_ESTADOS(DESC_ESTADO);
GO

-- Estados base 
INSERT INTO CAT.TBL_ESTADOS (DESC_ESTADO) VALUES ('ACTIVO'), ('INACTIVO');
GO

CREATE TABLE CAT.TBL_ROLES
(
    ID_ROL         INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ROLES PRIMARY KEY,
    DESC_ROL       VARCHAR(80) NOT NULL,
    FECHA_REGISTRO DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO      INT NOT NULL CONSTRAINT FK_ROLES_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO)
);
GO
CREATE UNIQUE INDEX UX_ROLES_DESC ON CAT.TBL_ROLES(DESC_ROL);
GO

-- Roles base 
INSERT INTO CAT.TBL_ROLES (DESC_ROL) VALUES ('ADMINISTRADOR'), ('DOCTOR'), ('ENFERMERO');
GO

CREATE TABLE CAT.TBL_TIPO_IDENTIFICACIONES
(
    ID_TIPO_IDENTIFICACION   INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TIPO_IDENT PRIMARY KEY,
    DESC_TIPO_IDENTIFICACION VARCHAR(20) NOT NULL,
    FECHA_REGISTRO           DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO                INT NOT NULL CONSTRAINT FK_TIPO_IDENT_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO)
);
GO
CREATE UNIQUE INDEX UX_TIPO_IDENT_DESC ON CAT.TBL_TIPO_IDENTIFICACIONES(DESC_TIPO_IDENTIFICACION);
GO

-- Tipo de identificaciones base 
INSERT INTO CAT.TBL_TIPO_IDENTIFICACIONES(DESC_TIPO_IDENTIFICACION) VALUES ('CEDULA'), ('PASAPORTE'), ('RESIDENCIA');
GO

CREATE TABLE CAT.TBL_GENERO
(
    ID_GENERO      INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_GENERO PRIMARY KEY,
    DESC_GENERO    VARCHAR(20) NOT NULL,
    FECHA_REGISTRO DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO      INT NOT NULL CONSTRAINT FK_GENERO_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO)
);
GO
CREATE UNIQUE INDEX UX_GENERO_DESC ON CAT.TBL_GENERO(DESC_GENERO);
GO

-- Generos base 
INSERT INTO CAT.TBL_GENERO(DESC_GENERO) VALUES ('MASCULINO'), ('FEMENINO'), ('COCHONES');
GO

CREATE TABLE CAT.TBL_TIPO_CONSULTA
(
    ID_TIPO_CONSULTA  INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TIPO_CONSULTA PRIMARY KEY,
    DESC_TIPO_CONSULTA VARCHAR(100) NOT NULL,
    PRECIO_CONSULTA   DECIMAL(18,4) NOT NULL,
    FECHA_REGISTRO    DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO         INT NOT NULL CONSTRAINT FK_TIPO_CONSULTA_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO)
);
GO
CREATE UNIQUE INDEX UX_TIPO_CONSULTA_DESC ON CAT.TBL_TIPO_CONSULTA(DESC_TIPO_CONSULTA);
GO

CREATE TABLE CAT.TBL_TIPO_DIAGNOSTICOS
(
    ID_TIPO_DIAGNOSTICO INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TIPO_DIAG PRIMARY KEY,
    DESC_DIAGNOSTICO    VARCHAR(100) NOT NULL,
    FECHA_REGISTRO      DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO           INT NOT NULL CONSTRAINT FK_TIPO_DIAG_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO)
);
GO
CREATE UNIQUE INDEX UX_TIPO_DIAG_DESC ON CAT.TBL_TIPO_DIAGNOSTICOS(DESC_DIAGNOSTICO);
GO

CREATE TABLE CAT.TBL_MEDICAMENTOS
(
    ID_MEDICAMENTO    INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_MEDICAMENTOS PRIMARY KEY,
    NOMBRE_GENERICO   VARCHAR(50) NULL,
    NOMBRE_COMERCIAL  VARCHAR(50) NULL,
    PRESENTACION      VARCHAR(50) NULL,
    CAT_MEDICAMENTO   VARCHAR(50) NULL,
    FECHA_REGISTRO    DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO         INT NOT NULL CONSTRAINT FK_MED_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO)
);
GO

CREATE TABLE CAT.TBL_TIPO_PROCEDIMIENTO
(
    ID_TIPO_PROCEDIMIENTO  INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TIPO_PROC PRIMARY KEY,
    DESC_TIPO_PROCEDIMIENTO VARCHAR(100) NOT NULL,
    FECHA_REGISTRO          DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO               INT NOT NULL CONSTRAINT FK_TIPO_PROC_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO)
);
GO
CREATE UNIQUE INDEX UX_TIPO_PROC_DESC ON CAT.TBL_TIPO_PROCEDIMIENTO(DESC_TIPO_PROCEDIMIENTO);
GO

CREATE TABLE CAT.TBL_TIPO_EXAMEN
(
    ID_TIPO_EXAMEN  INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TIPO_EXAMEN PRIMARY KEY,
    DESC_TIPO_EXAMEN VARCHAR(100) NOT NULL,
    FECHA_REGISTRO   DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO        INT NOT NULL CONSTRAINT FK_TIPO_EXAMEN_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO)
);
GO
CREATE UNIQUE INDEX UX_TIPO_EXAMEN_DESC ON CAT.TBL_TIPO_EXAMEN(DESC_TIPO_EXAMEN);
GO

/* =========================
		TABLAS GENERALES
   ========================= */

CREATE TABLE CLI.TBL_CONTACTO_EMERGENCIA
(
    ID_CONTACTO_EMERGENCIA INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CONTACTO_EMERGENCIA PRIMARY KEY,
    NOMBRE_CONTACTO        VARCHAR(100) NOT NULL,
    PARENTESCO             VARCHAR(50)  NOT NULL,
    TELEFONO               VARCHAR(20)  NOT NULL,
    EMAIL                  VARCHAR(100) NULL,
    DIRECCION              VARCHAR(MAX) NOT NULL,
    FECHA_REGISTRO         DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO              INT NOT NULL CONSTRAINT FK_CONTACTO_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO)
);
GO

CREATE TABLE ADM.TBL_PERSONAS
(
    ID_PERSONAS            INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PERSONAS PRIMARY KEY,
    PRIMER_NOMBRE          VARCHAR(20) NOT NULL,
    SEGUNDO_NOMBRE         VARCHAR(20) NULL,
    PRIMER_APELLIDO        VARCHAR(20) NOT NULL,
    SEGUNDO_APELLIDO       VARCHAR(20) NULL,
    ID_TIPO_IDENTIFICACION INT NOT NULL CONSTRAINT FK_PERSONAS_TIPO_IDENT REFERENCES CAT.TBL_TIPO_IDENTIFICACIONES(ID_TIPO_IDENTIFICACION),
    DESC_IDENTIFICACION    VARCHAR(25) NOT NULL,
    ID_GENERO              INT NOT NULL CONSTRAINT FK_PERSONAS_GENERO REFERENCES CAT.TBL_GENERO(ID_GENERO),
    FECHA_NACIMIENTO       DATE NOT NULL,
    EMAIL                  VARCHAR(100) NULL,
    TELEFONO               VARCHAR(20) NOT NULL,
    DIRECCION              VARCHAR(MAX) NOT NULL,
    FECHA_REGISTRO         DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO              INT NOT NULL CONSTRAINT FK_PERSONAS_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO),
    CONSTRAINT UQ_PERSONA_IDENTIFICACION UNIQUE (ID_TIPO_IDENTIFICACION, DESC_IDENTIFICACION)
);
GO

CREATE TABLE ADM.TBL_EMPLEADOS
(
    ID_EMPLEADOS   INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_EMPLEADOS PRIMARY KEY,
    ID_PERSONAS    INT NOT NULL CONSTRAINT FK_EMPLEADOS_PERSONAS REFERENCES ADM.TBL_PERSONAS(ID_PERSONAS),
    ID_ROL         INT NOT NULL CONSTRAINT FK_EMPLEADOS_ROLES REFERENCES CAT.TBL_ROLES(ID_ROL),
    FECHA_REGISTRO DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO      INT NOT NULL CONSTRAINT FK_EMPLEADOS_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO)
);
GO

/* =================
		Usuarios 
   =================
*/
CREATE TABLE ADM.TBL_USUARIOS
(
    ID_USUARIO       INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_USUARIOS PRIMARY KEY,
    USUARIO          VARCHAR(80) NOT NULL,
	CONTRASENA		 VARCHAR(50) NOT NULL,

    ID_EMPLEADOS     INT NULL CONSTRAINT FK_USUARIOS_EMPLEADOS REFERENCES ADM.TBL_EMPLEADOS(ID_EMPLEADOS),
    ID_ROL           INT NOT NULL CONSTRAINT FK_USUARIOS_ROLES REFERENCES CAT.TBL_ROLES(ID_ROL),

    FECHA_REGISTRO   DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO        INT NOT NULL CONSTRAINT FK_USUARIOS_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO)
);
GO

CREATE UNIQUE INDEX UX_USUARIOS_USUARIO ON ADM.TBL_USUARIOS(USUARIO);
GO

-- Un usuario por empleado. Filtrado para permitir NULL.
CREATE UNIQUE INDEX UX_USUARIOS_EMPLEADO ON ADM.TBL_USUARIOS(ID_EMPLEADOS) WHERE ID_EMPLEADOS IS NOT NULL;
GO

CREATE TABLE CLI.TBL_CLIENTES
(
    ID_CLIENTE             INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CLIENTES PRIMARY KEY,
    ID_PERSONAS            INT NOT NULL CONSTRAINT FK_CLIENTES_PERSONAS REFERENCES ADM.TBL_PERSONAS(ID_PERSONAS),
    OCUPACION              VARCHAR(100) NULL,
    ID_CONTACTO_EMERGENCIA INT NULL CONSTRAINT FK_CLIENTES_CONTACTO REFERENCES CLI.TBL_CONTACTO_EMERGENCIA(ID_CONTACTO_EMERGENCIA),
    FECHA_REGISTRO         DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO              INT NOT NULL CONSTRAINT FK_CLIENTES_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO)
);
GO

/* ===========================
		CITAS / CONSULTAS
   =========================== */

CREATE TABLE ADM.TBL_CITAS
(
    ID_CITA        INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CITAS PRIMARY KEY,
    ID_PERSONAS    INT NOT NULL CONSTRAINT FK_CITAS_PERSONAS REFERENCES ADM.TBL_PERSONAS(ID_PERSONAS),
    FECHA          DATE NOT NULL,
    HORA_INICIO    TIME NOT NULL,
    HORA_FIN       TIME NOT NULL,
    DESC_CITA      VARCHAR(MAX) NULL,
    FECHA_REGISTRO DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO      INT NOT NULL CONSTRAINT FK_CITAS_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO),
    CONSTRAINT CK_CITAS_HORAS CHECK (HORA_FIN > HORA_INICIO)
);
GO

CREATE INDEX IX_CITAS_PERSONA_FECHA ON ADM.TBL_CITAS(ID_PERSONAS, FECHA);
GO

/* CONSULTA depende de CITA */
CREATE TABLE ADM.TBL_CONSULTA
(
    ID_CONSULTA     INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CONSULTA PRIMARY KEY,
    ID_CITA         INT NOT NULL CONSTRAINT FK_CONSULTA_CITAS REFERENCES ADM.TBL_CITAS(ID_CITA),
    ID_EMPLEADOS    INT NOT NULL CONSTRAINT FK_CONSULTA_EMPLEADOS REFERENCES ADM.TBL_EMPLEADOS(ID_EMPLEADOS),
    ID_TIPO_CONSULTA INT NOT NULL CONSTRAINT FK_CONSULTA_TIPO REFERENCES CAT.TBL_TIPO_CONSULTA(ID_TIPO_CONSULTA),

    FECHA_REGISTRO  DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO       INT NOT NULL CONSTRAINT FK_CONSULTA_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO)
);
GO

-- Índices típicos: por médico, por cita (y la persona se obtiene desde CITA)
CREATE INDEX IX_CONSULTA_MEDICO_FECHA ON ADM.TBL_CONSULTA(ID_EMPLEADOS, FECHA_REGISTRO);
GO
CREATE INDEX IX_CONSULTA_CITA ON ADM.TBL_CONSULTA(ID_CITA);
GO

/* Detalle clínico 1:1 */
CREATE TABLE ADM.TBL_DETALLES_CONSULTA
(
    ID_CONSULTA     INT NOT NULL CONSTRAINT PK_DET_CONSULTA PRIMARY KEY CONSTRAINT FK_DET_CONSULTA_CONSULTA REFERENCES ADM.TBL_CONSULTA(ID_CONSULTA),
    OBSERVACIONES   VARCHAR(MAX) NULL,
    RECOMENDACIONES VARCHAR(MAX) NULL,
    FECHA_REGISTRO  DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO       INT NOT NULL CONSTRAINT FK_DET_CONSULTA_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO)
);
GO

/* Diagnósticos (N por consulta) */
CREATE TABLE CLI.TBL_DIAGNOSTICOS
(
    ID_DIAGNOSTICO      INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_DIAGNOSTICOS PRIMARY KEY,
    ID_CONSULTA         INT NOT NULL CONSTRAINT FK_DIAG_CONSULTA REFERENCES ADM.TBL_CONSULTA(ID_CONSULTA),
    ID_TIPO_DIAGNOSTICO INT NOT NULL CONSTRAINT FK_DIAG_TIPO REFERENCES CAT.TBL_TIPO_DIAGNOSTICOS(ID_TIPO_DIAGNOSTICO),
    NOTAS               VARCHAR(MAX) NULL,
    FECHA_REGISTRO      DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO           INT NOT NULL CONSTRAINT FK_DIAG_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO),
    CONSTRAINT UQ_CONSULTA_DIAG UNIQUE (ID_CONSULTA, ID_TIPO_DIAGNOSTICO)
);
GO

/* Tratamientos (detalle de receta) */
CREATE TABLE CLI.TBL_TRATAMIENTOS
(
    ID_TRATAMIENTO       INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TRATAMIENTOS PRIMARY KEY,
    ID_MEDICAMENTO       INT NULL CONSTRAINT FK_TRAT_MED REFERENCES CAT.TBL_MEDICAMENTOS(ID_MEDICAMENTO),
    DOSIS                VARCHAR(100) NULL,
    VIA_ADMINISTRACION   VARCHAR(100) NULL,
    FRECUENCIA           VARCHAR(100) NULL,
    DURACION_TRATAMIENTO VARCHAR(100) NULL,
    IND_ESPECIFICAS      VARCHAR(MAX) NULL,
    FECHA_REGISTRO       DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO            INT NOT NULL CONSTRAINT FK_TRAT_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO)
);
GO

CREATE TABLE ADM.TBL_CONSULTA_TRATAMIENTO
(
    ID_CONSULTA_TRATAMIENTO INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CONS_TRAT PRIMARY KEY,
    ID_CONSULTA             INT NOT NULL CONSTRAINT FK_CONS_TRAT_CONSULTA REFERENCES ADM.TBL_CONSULTA(ID_CONSULTA),
    ID_TRATAMIENTO          INT NOT NULL CONSTRAINT FK_CONS_TRAT_TRAT REFERENCES CLI.TBL_TRATAMIENTOS(ID_TRATAMIENTO),
    FECHA_REGISTRO          DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO               INT NOT NULL CONSTRAINT FK_CONS_TRAT_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO),

    CONSTRAINT UQ_CONSULTA_TRATAMIENTO UNIQUE (ID_CONSULTA, ID_TRATAMIENTO)
);
GO

/* Exámenes (N por consulta) */
CREATE TABLE ADM.TBL_CONSULTA_EXAMEN
(
    ID_CONSULTA_EXAMEN INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CONS_EXAM PRIMARY KEY,
    ID_CONSULTA        INT NOT NULL CONSTRAINT FK_CONS_EXAM_CONSULTA REFERENCES ADM.TBL_CONSULTA(ID_CONSULTA),
    ID_TIPO_EXAMEN     INT NOT NULL CONSTRAINT FK_CONS_EXAM_TIPO REFERENCES CAT.TBL_TIPO_EXAMEN(ID_TIPO_EXAMEN),
    RESULTADO          VARCHAR(MAX) NULL,
    FECHA_REGISTRO     DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO          INT NOT NULL CONSTRAINT FK_CONS_EXAM_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO),

    CONSTRAINT UQ_CONSULTA_EXAMEN UNIQUE (ID_CONSULTA, ID_TIPO_EXAMEN)
);
GO

/* Signos vitales (1 por consulta) */
CREATE TABLE CLI.TBL_SIGNOS_VITALES
(
    ID_SIGNOS_VITALES        INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_SIGNOS PRIMARY KEY,
    ID_CONSULTA              INT NOT NULL CONSTRAINT FK_SIGNOS_CONSULTA REFERENCES ADM.TBL_CONSULTA(ID_CONSULTA),

    PRESION_ARTERIAL         VARCHAR(15) NULL,      -- ej: 120/80
    FRECUENCIA_CARDIACA      SMALLINT NULL,         -- bpm
    FRECUENCIA_RESPIRATORIA  SMALLINT NULL,         -- rpm
    TEMPERATURA_CORPORAL     DECIMAL(4,2) NULL,     -- 36.50
    SATURACION_OXIGENO       DECIMAL(5,2) NULL,     -- 98.00
    PESO                     DECIMAL(6,2) NULL,     -- 9999.99
    ALTURA                   DECIMAL(4,2) NULL,     -- 2.10
    MASA_CORPORAL            DECIMAL(5,2) NULL,     -- 45.50
    OBSERVACIONES            VARCHAR(MAX) NULL,

    FECHA_REGISTRO           DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO                INT NOT NULL CONSTRAINT FK_SIGNOS_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO)
);
GO

CREATE UNIQUE INDEX UX_SIGNOS_CONSULTA ON CLI.TBL_SIGNOS_VITALES(ID_CONSULTA);
GO

/* Procedimientos (N por consulta) */
CREATE TABLE ADM.TBL_PROCEDIMIENTO
(
    ID_PROCEDIMIENTO      INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PROCEDIMIENTO PRIMARY KEY,
    ID_CONSULTA           INT NOT NULL CONSTRAINT FK_PROC_CONSULTA REFERENCES ADM.TBL_CONSULTA(ID_CONSULTA),
    ID_TIPO_PROCEDIMIENTO INT NOT NULL CONSTRAINT FK_PROC_TIPO REFERENCES CAT.TBL_TIPO_PROCEDIMIENTO(ID_TIPO_PROCEDIMIENTO),
    NOTAS                 VARCHAR(MAX) NULL,
    FECHA_REGISTRO        DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ID_ESTADO             INT NOT NULL CONSTRAINT FK_PROC_ESTADOS REFERENCES CAT.TBL_ESTADOS(ID_ESTADO)
);
GO

/* =========================
   SP guardar usuario (en desarrollo)
   ========================= */
CREATE OR ALTER PROCEDURE ADM.SP_USUARIO_CREAR
    @USUARIO          VARCHAR(80),
    @PASSWORD_HASH    VARBINARY(64),
    @PASSWORD_SALT    VARBINARY(16),
    @HASH_ALGO        VARCHAR(20) = 'PBKDF2',
    @HASH_ITERATIONS  INT = 100000,
    @ID_EMPLEADOS     INT = NULL,
    @ID_ROL           INT,
    @ID_ESTADO        INT = 1
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM ADM.TBL_USUARIOS WHERE USUARIO = @USUARIO)
        THROW 50001, 'El usuario ya existe.', 1;

    INSERT INTO ADM.TBL_USUARIOS
    (
        USUARIO, PASSWORD_HASH, PASSWORD_SALT, HASH_ALGO, HASH_ITERATIONS,
        ID_EMPLEADOS, ID_ROL, ID_ESTADO
    )
    VALUES
    (
        @USUARIO, @PASSWORD_HASH, @PASSWORD_SALT, @HASH_ALGO, @HASH_ITERATIONS,
        @ID_EMPLEADOS, @ID_ROL, @ID_ESTADO
    );

    SELECT SCOPE_IDENTITY() AS ID_USUARIO;
END
GO