/*========================================================
MEDITECH DB v4.0 - Edición Evolución Clínica + Inventario
Arquitectura profesional con gestión de prospectos y ventas
========================================================*/

-- CREATE DATABASE MediTech;
-- GO

USE MediTech;
GO

/*========================================================
SCHEMAS
========================================================*/

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'CAT') EXEC('CREATE SCHEMA CAT');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'ADM') EXEC('CREATE SCHEMA ADM');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'CLI') EXEC('CREATE SCHEMA CLI');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'DOC') EXEC('CREATE SCHEMA DOC');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'CAJA') EXEC('CREATE SCHEMA CAJA');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'INV') EXEC('CREATE SCHEMA INV');
GO

/*========================================================
CATALOGOS
========================================================*/

CREATE TABLE CAT.ESTADOS(
    ID_ESTADO INT IDENTITY(1,1) CONSTRAINT PK_ESTADOS PRIMARY KEY,
    DESC_ESTADO VARCHAR(50) NOT NULL,
    FECHA_CREACION DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    FECHA_ACTUALIZACION DATETIME2 NULL,
    USUARIO_MODIFICACION VARCHAR(80) NULL
);

INSERT INTO CAT.ESTADOS (DESC_ESTADO) VALUES ('ACTIVO'), ('INACTIVO'), ('ANULADO');
GO

CREATE TABLE CAT.ROLES(
    ID_ROL INT IDENTITY PRIMARY KEY,
    DESC_ROL VARCHAR(80) NOT NULL,
    ID_ESTADO INT NOT NULL DEFAULT 1,
    FECHA_CREACION DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);

INSERT INTO CAT.ROLES (DESC_ROL, ID_ESTADO) VALUES ('ADMINISTRADOR', 1), ('DOCTOR', 1), ('ASISTENTE', 1);
GO

CREATE TABLE CAT.TIPO_IDENTIFICACION(
    ID_TIPO_IDENTIFICACION INT IDENTITY PRIMARY KEY,
    DESC_TIPO VARCHAR(50) NOT NULL,
    ID_ESTADO INT NOT NULL DEFAULT 1,
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);

INSERT INTO CAT.TIPO_IDENTIFICACION (DESC_TIPO, ID_ESTADO) VALUES ('CEDULA', 1), ('PASAPORTE', 1), ('RESIDENCIA', 1);
GO

CREATE TABLE CAT.GENEROS(
    ID_GENERO INT IDENTITY PRIMARY KEY,
    DESC_GENERO VARCHAR(20),
    ID_ESTADO INT NOT NULL DEFAULT 1,
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);

INSERT INTO CAT.GENEROS(DESC_GENERO, ID_ESTADO) VALUES ('MASCULINO', 1), ('FEMENINO', 1), ('OTRO', 1);
GO

CREATE TABLE CAT.MONEDAS(
    ID_MONEDA INT IDENTITY CONSTRAINT PK_MONEDAS PRIMARY KEY,
    CODIGO VARCHAR(10) NOT NULL, -- USD / NIO
    NOMBRE VARCHAR(50) NOT NULL,
    SIMBOLO VARCHAR(5)
);

INSERT INTO CAT.MONEDAS (CODIGO,NOMBRE,SIMBOLO)
VALUES ('USD','DOLAR','$'), ('NIO','CORDOBA','C$');
GO

-- NUEVOS CATALOGOS v4.0 Normalización

CREATE TABLE CAT.TIPO_ASISTENCIA(
    ID_TIPO_ASISTENCIA INT IDENTITY PRIMARY KEY,
    DESC_ASISTENCIA VARCHAR(50) NOT NULL, -- CONFIRMADO, LLEGO, NO_LLEGO, REPROGRAMADO
    COLOR VARCHAR(20), -- Azul, Verde, Rojo, Amarillo
    ID_ESTADO INT NOT NULL DEFAULT 1,
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);

INSERT INTO CAT.TIPO_ASISTENCIA (DESC_ASISTENCIA, COLOR) VALUES 
('CONFIRMADO', '#0000FF'), 
('LLEGÓ', '#00FF00'), 
('NO LLEGÓ', '#FF0000'), 
('REPROGRAMADO', '#FFFF00');
GO

CREATE TABLE CAT.ESTADO_CITA(
    ID_ESTADO_CITA INT IDENTITY PRIMARY KEY,
    DESC_ESTADO_CITA VARCHAR(50) NOT NULL, -- PROGRAMADA, EN_CURSO, FINALIZADA, CANCELADA, NO_ASISTIO
    ID_ESTADO INT NOT NULL DEFAULT 1,
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);

INSERT INTO CAT.ESTADO_CITA (DESC_ESTADO_CITA) VALUES 
('PROGRAMADA'), ('EN CURSO'), ('FINALIZADA'), ('CANCELADA'), ('NO ASISTIÓ');
GO

CREATE TABLE CAT.MODULOS(
    ID_MODULO INT IDENTITY CONSTRAINT PK_MODULOS PRIMARY KEY,
    NOMBRE_MODULO VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(200),
    FECHA_CREACION DATETIME2 DEFAULT SYSDATETIME(),
    ID_ESTADO INT DEFAULT 1,
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);

INSERT INTO CAT.MODULOS (NOMBRE_MODULO, DESCRIPCION) VALUES
('Dashboard','Panel principal del sistema'),
('Citas','Gestión de agenda médica'),
('Pacientes','Administración de pacientes'),
('Consultas','Registro de consultas médicas'),
('Tratamientos','Catálogo de tratamientos'),
('Inventario','Control de productos'),
('Caja y Pagos','Gestión de pagos y caja'),
('Reportes','Reportes administrativos'),
('Configuracion','Configuración del sistema');
GO

/*========================================================
TRATAMIENTOS (ENRIQUECIDO)
========================================================*/

CREATE TABLE CAT.TRATAMIENTOS(
    ID_TRATAMIENTO INT IDENTITY CONSTRAINT PK_TRATAMIENTOS PRIMARY KEY,
    NOMBRE_TRATAMIENTO VARCHAR(200) NOT NULL,
    PRECIO DECIMAL(12,2),
    ID_MONEDA INT NULL, -- Multimoneda
    DOSIS VARCHAR(100) NULL,
    VIA_ADMINISTRACION VARCHAR(100) NULL,
    FRECUENCIA VARCHAR(100) NULL,
    DURACION_TRATAMIENTO VARCHAR(100) NULL,
    ID_ESTADO INT DEFAULT 1,
    FECHA_ACTUALIZACION DATETIME2 NULL,
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO),
    FOREIGN KEY(ID_MONEDA) REFERENCES CAT.MONEDAS(ID_MONEDA)
);
GO

/*========================================================
ADMINISTRACIÓN Y CONFIGURACIÓN
========================================================*/

CREATE TABLE ADM.CONFIGURACION_MONEDA(
    ID_CONFIGURACION INT IDENTITY CONSTRAINT PK_CONFIG_MONEDA PRIMARY KEY,
    ID_MONEDA_BASE INT NOT NULL,
    TASA_CAMBIO DECIMAL(12,4) NOT NULL,
    FECHA_ACTUALIZACION DATETIME2 DEFAULT SYSDATETIME(),
    USUARIO_MODIFICACION VARCHAR(80),
    FOREIGN KEY(ID_MONEDA_BASE) REFERENCES CAT.MONEDAS(ID_MONEDA)
);
GO

CREATE TABLE ADM.PERSONAS(
    ID_PERSONA INT IDENTITY CONSTRAINT PK_PERSONAS PRIMARY KEY,
    PRIMER_NOMBRE VARCHAR(40) NOT NULL,
    SEGUNDO_NOMBRE VARCHAR(40),
    PRIMER_APELLIDO VARCHAR(40) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR(40),
    ID_TIPO_IDENTIFICACION INT NOT NULL,
    NUM_IDENTIFICACION VARCHAR(25) NOT NULL,
    ID_GENERO INT NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    EMAIL VARCHAR(120),
    TELEFONO VARCHAR(20) NOT NULL,
    DIRECCION VARCHAR(250),
    FECHA_CREACION DATETIME2 DEFAULT SYSDATETIME(),
    FECHA_ACTUALIZACION DATETIME2 NULL,
    USUARIO_MODIFICACION VARCHAR(80) NULL,
    ID_ESTADO INT NOT NULL DEFAULT 1,
    CONSTRAINT UQ_IDENTIFICACION UNIQUE(ID_TIPO_IDENTIFICACION,NUM_IDENTIFICACION),
    FOREIGN KEY(ID_TIPO_IDENTIFICACION) REFERENCES CAT.TIPO_IDENTIFICACION(ID_TIPO_IDENTIFICACION),
    FOREIGN KEY(ID_GENERO) REFERENCES CAT.GENEROS(ID_GENERO),
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);
GO

CREATE INDEX IX_PERSONA_APELLIDO ON ADM.PERSONAS(PRIMER_APELLIDO);
GO

CREATE TABLE ADM.EMPLEADOS(
    ID_EMPLEADO INT IDENTITY CONSTRAINT PK_EMPLEADOS PRIMARY KEY,
    ID_PERSONA INT NOT NULL,
    ID_ROL INT NOT NULL,
    FECHA_CONTRATACION DATE,
    ID_ESTADO INT DEFAULT 1,
    FOREIGN KEY(ID_PERSONA) REFERENCES ADM.PERSONAS(ID_PERSONA),
    FOREIGN KEY(ID_ROL) REFERENCES CAT.ROLES(ID_ROL),
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);
GO

CREATE TABLE ADM.PERMISOS_ROL(
    ID_PERMISO INT IDENTITY CONSTRAINT PK_PERMISOS_ROL PRIMARY KEY,
    ID_ROL INT NOT NULL,
    ID_MODULO INT NOT NULL,
    PUEDE_VER BIT DEFAULT 1,
    PUEDE_CREAR BIT DEFAULT 0,
    PUEDE_EDITAR BIT DEFAULT 0,
    PUEDE_ELIMINAR BIT DEFAULT 0,
    FECHA_CREACION DATETIME2 DEFAULT SYSDATETIME(),
    FOREIGN KEY(ID_ROL) REFERENCES CAT.ROLES(ID_ROL),
    FOREIGN KEY(ID_MODULO) REFERENCES CAT.MODULOS(ID_MODULO)
);

CREATE INDEX IX_PERMISOS_ROL ON ADM.PERMISOS_ROL(ID_ROL, ID_MODULO);
GO

-- CONFIGURACION INICIAL DE PERMISOS
INSERT INTO ADM.PERMISOS_ROL (ID_ROL, ID_MODULO, PUEDE_VER, PUEDE_CREAR, PUEDE_EDITAR, PUEDE_ELIMINAR)
SELECT R.ID_ROL, M.ID_MODULO, 1, 1, 1, 1 FROM CAT.ROLES R CROSS JOIN CAT.MODULOS M WHERE R.DESC_ROL = 'ADMINISTRADOR';

INSERT INTO ADM.PERMISOS_ROL (ID_ROL, ID_MODULO, PUEDE_VER, PUEDE_CREAR, PUEDE_EDITAR, PUEDE_ELIMINAR)
SELECT R.ID_ROL, M.ID_MODULO, 1, 1, 1, 0 FROM CAT.ROLES R JOIN CAT.MODULOS M ON M.NOMBRE_MODULO IN ('Dashboard', 'Citas', 'Pacientes', 'Consultas', 'Tratamientos') WHERE R.DESC_ROL = 'DOCTOR';

INSERT INTO ADM.PERMISOS_ROL (ID_ROL, ID_MODULO, PUEDE_VER, PUEDE_CREAR, PUEDE_EDITAR, PUEDE_ELIMINAR)
SELECT R.ID_ROL, M.ID_MODULO, 1, 1, 0, 0 FROM CAT.ROLES R JOIN CAT.MODULOS M ON M.NOMBRE_MODULO IN ('Dashboard', 'Citas', 'Pacientes', 'Caja y Pagos') WHERE R.DESC_ROL = 'ASISTENTE';
GO

CREATE TABLE ADM.USUARIOS(
    ID_USUARIO INT IDENTITY CONSTRAINT PK_USUARIOS PRIMARY KEY,
    USERNAME VARCHAR(80) NOT NULL UNIQUE,
    PASSWORD_HASH VARBINARY(256),
    PASSWORD_SALT VARBINARY(128),
    ID_EMPLEADO INT,
    ID_ROL INT,
    FECHA_CREACION DATETIME2 DEFAULT SYSDATETIME(),
    FECHA_ACTUALIZACION DATETIME2 NULL,
    USUARIO_MODIFICACION VARCHAR(80) NULL,
    ID_ESTADO INT,
    FOREIGN KEY(ID_EMPLEADO) REFERENCES ADM.EMPLEADOS(ID_EMPLEADO),
    FOREIGN KEY(ID_ROL) REFERENCES CAT.ROLES(ID_ROL),
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);
GO

/*========================================================
PACIENTES Y CITAS
========================================================*/

CREATE TABLE CLI.PACIENTES(
    ID_PACIENTE INT IDENTITY CONSTRAINT PK_PACIENTES PRIMARY KEY,
    ID_PERSONA INT NOT NULL,
    OCUPACION VARCHAR(100),
    CONTACTO_EMERGENCIA VARCHAR(120),
    TELEFONO_EMERGENCIA VARCHAR(20),
    FECHA_REGISTRO DATETIME2 DEFAULT SYSDATETIME(),
    FECHA_ACTUALIZACION DATETIME2 NULL,
    USUARIO_MODIFICACION VARCHAR(80) NULL,
    ID_ESTADO INT DEFAULT 1,
    FOREIGN KEY(ID_PERSONA) REFERENCES ADM.PERSONAS(ID_PERSONA),
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);
GO

CREATE TABLE CLI.POSIBLES_PACIENTES(
    ID_POSIBLE_PACIENTE INT IDENTITY CONSTRAINT PK_POSIBLE_PACIENTE PRIMARY KEY,
    PRIMER_NOMBRE VARCHAR(40) NOT NULL,
    SEGUNDO_NOMBRE VARCHAR(40),
    PRIMER_APELLIDO VARCHAR(40) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR(40),
    TELEFONO VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME2 DEFAULT SYSDATETIME(),
    ID_ESTADO INT DEFAULT 1,
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);
GO

CREATE TABLE CLI.CITAS(
    ID_CITA INT IDENTITY CONSTRAINT PK_CITAS PRIMARY KEY,
    ID_PACIENTE INT NULL, 
    ID_POSIBLE_PACIENTE INT NULL, 
    ID_TRATAMIENTO INT,
    ID_ESTADO_CITA INT NOT NULL DEFAULT 1,
    FECHA DATE NOT NULL,
    HORA_INICIO TIME NOT NULL,
    HORA_FIN TIME NOT NULL,
    OBSERVACIONES VARCHAR(300),
    FECHA_CREACION DATETIME2 DEFAULT SYSDATETIME(),
    FECHA_ACTUALIZACION DATETIME2 NULL,
    USUARIO_MODIFICACION VARCHAR(80) NULL,
    ID_ESTADO INT DEFAULT 1,
    FOREIGN KEY(ID_PACIENTE) REFERENCES CLI.PACIENTES(ID_PACIENTE),
    FOREIGN KEY(ID_POSIBLE_PACIENTE) REFERENCES CLI.POSIBLES_PACIENTES(ID_POSIBLE_PACIENTE),
    FOREIGN KEY(ID_TRATAMIENTO) REFERENCES CAT.TRATAMIENTOS(ID_TRATAMIENTO),
    FOREIGN KEY(ID_ESTADO_CITA) REFERENCES CAT.ESTADO_CITA(ID_ESTADO_CITA),
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);
GO

CREATE INDEX IX_CITAS_FECHA ON CLI.CITAS(FECHA);
GO

CREATE TABLE CLI.ASISTENCIA_CITAS(
    ID_ASISTENCIA INT IDENTITY CONSTRAINT PK_ASISTENCIA_CITA PRIMARY KEY,
    ID_CITA INT NOT NULL,
    ID_TIPO_ASISTENCIA INT NOT NULL,
    FECHA_REGISTRO DATETIME2 DEFAULT SYSDATETIME(),
    OBSERVACION VARCHAR(200),
    FOREIGN KEY(ID_CITA) REFERENCES CLI.CITAS(ID_CITA),
    FOREIGN KEY(ID_TIPO_ASISTENCIA) REFERENCES CAT.TIPO_ASISTENCIA(ID_TIPO_ASISTENCIA)
);
GO

CREATE TABLE CLI.CONSULTAS(
    ID_CONSULTA INT IDENTITY CONSTRAINT PK_CONSULTAS PRIMARY KEY,
    ID_CITA INT NOT NULL,
    ID_MEDICO INT NOT NULL,
    MOTIVO_CONSULTA VARCHAR(300),
    DIAGNOSTICO_PRINCIPAL VARCHAR(500),
    OBSERVACIONES VARCHAR(500),
    FECHA_CONSULTA DATETIME2 DEFAULT SYSDATETIME(),
    ID_ESTADO INT DEFAULT 1,
    FOREIGN KEY(ID_CITA) REFERENCES CLI.CITAS(ID_CITA),
    FOREIGN KEY(ID_MEDICO) REFERENCES ADM.EMPLEADOS(ID_EMPLEADO),
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);
GO

CREATE TABLE CLI.DIAGNOSTICOS(
    ID_DIAGNOSTICO INT IDENTITY CONSTRAINT PK_DIAGNOSTICOS PRIMARY KEY,
    ID_CONSULTA INT NOT NULL,
    DESCRIPCION VARCHAR(250) NOT NULL,
    NOTAS VARCHAR(MAX) NULL,
    FECHA_REGISTRO DATETIME2 DEFAULT SYSDATETIME(),
    ID_ESTADO INT NOT NULL DEFAULT 1,
    FOREIGN KEY(ID_CONSULTA) REFERENCES CLI.CONSULTAS(ID_CONSULTA),
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);
GO

CREATE TABLE CLI.SIGNOS_VITALES(
    ID_SIGNOS INT IDENTITY CONSTRAINT PK_SIGNOS PRIMARY KEY,
    ID_CONSULTA INT UNIQUE,
    PRESION_ARTERIAL VARCHAR(15),
    TEMPERATURA DECIMAL(5,2),
    FRECUENCIA_CARDIACA INT,
    SATURACION_OXIGENO INT,
    PESO DECIMAL(5,2),
    ALTURA DECIMAL(5,2),
    FOREIGN KEY(ID_CONSULTA) REFERENCES CLI.CONSULTAS(ID_CONSULTA)
);
GO

/*========================================================
INVENTARIO
========================================================*/

CREATE TABLE INV.PRODUCTOS(
    ID_PRODUCTO INT IDENTITY CONSTRAINT PK_PRODUCTOS PRIMARY KEY,
    NOMBRE VARCHAR(120) NOT NULL,
    DESCRIPCION VARCHAR(300),
    PRECIO DECIMAL(12,2),
    ID_MONEDA INT NULL, -- Multimoneda
    STOCK INT DEFAULT 0,
    STOCK_MINIMO INT DEFAULT 0,
    ACTIVO BIT DEFAULT 1,
    FECHA_CREACION DATETIME2 DEFAULT SYSDATETIME(),
    FOREIGN KEY(ID_MONEDA) REFERENCES CAT.MONEDAS(ID_MONEDA)
);
GO

-- REGLA DE NEGOCIO: No permitir stock negativo
ALTER TABLE INV.PRODUCTOS 
ADD CONSTRAINT CHK_PRODUCTO_STOCK_POSITIVO 
CHECK (STOCK >= 0);
GO

CREATE TABLE INV.MOVIMIENTOS_INVENTARIO(
    ID_MOVIMIENTO INT IDENTITY CONSTRAINT PK_MOVIMIENTO PRIMARY KEY,
    ID_PRODUCTO INT NOT NULL,
    TIPO_MOVIMIENTO VARCHAR(20), -- COMPRA, VENTA, AJUSTE
    CANTIDAD INT,
    FECHA_MOVIMIENTO DATETIME2 DEFAULT SYSDATETIME(),
    OBSERVACION VARCHAR(200),
    FOREIGN KEY(ID_PRODUCTO) REFERENCES INV.PRODUCTOS(ID_PRODUCTO)
);
GO

/*========================================================
CAJA Y FINANZAS (MODULO INTEGRAL v4.0)
========================================================*/

CREATE TABLE CAJA.CUENTAS(
    ID_CUENTA INT IDENTITY CONSTRAINT PK_CUENTAS PRIMARY KEY,
    ID_PACIENTE INT,
    ID_CONSULTA INT,
    TOTAL_BRUTO DECIMAL(12,2),
    DESCUENTO DECIMAL(12,2) DEFAULT 0,
    TOTAL_FINAL DECIMAL(12,2),
    ID_MONEDA_BASE INT,
    FECHA_CREACION DATETIME2 DEFAULT SYSDATETIME(),
    FOREIGN KEY(ID_PACIENTE) REFERENCES CLI.PACIENTES(ID_PACIENTE),
    FOREIGN KEY(ID_CONSULTA) REFERENCES CLI.CONSULTAS(ID_CONSULTA),
    FOREIGN KEY(ID_MONEDA_BASE) REFERENCES CAT.MONEDAS(ID_MONEDA)
);

CREATE INDEX IX_CUENTAS_FECHA ON CAJA.CUENTAS(FECHA_CREACION);
GO

CREATE TABLE CAJA.CUENTA_DETALLE(
    ID_DETALLE INT IDENTITY CONSTRAINT PK_CUENTA_DETALLE PRIMARY KEY,
    ID_CUENTA INT NOT NULL,
    TIPO_ITEM VARCHAR(20), -- TRATAMIENTO / PRODUCTO
    ID_REFERENCIA INT,
    DESCRIPCION VARCHAR(200),
    CANTIDAD INT,
    PRECIO_UNITARIO DECIMAL(12,2),
    SUBTOTAL DECIMAL(12,2),
    FOREIGN KEY(ID_CUENTA) REFERENCES CAJA.CUENTAS(ID_CUENTA)
);

CREATE INDEX IX_CUENTA_DETALLE_CUENTA ON CAJA.CUENTA_DETALLE(ID_CUENTA);
GO

CREATE TABLE CAJA.PAGOS(
    ID_PAGO INT IDENTITY CONSTRAINT PK_PAGOS PRIMARY KEY,
    ID_CUENTA INT NOT NULL,
    MONTO DECIMAL(12,2),
    ID_MONEDA INT,
    METODO_PAGO VARCHAR(30), -- EFECTIVO, TARJETA, TRANSFERENCIA
    TASA_CAMBIO_APLICADA DECIMAL(12,4),
    FECHA_PAGO DATETIME2 DEFAULT SYSDATETIME(),
    FOREIGN KEY(ID_CUENTA) REFERENCES CAJA.CUENTAS(ID_CUENTA),
    FOREIGN KEY(ID_MONEDA) REFERENCES CAT.MONEDAS(ID_MONEDA)
);

CREATE INDEX IX_PAGOS_FECHA ON CAJA.PAGOS(FECHA_PAGO);
GO

/*========================================================
DOCS Y OTROS
========================================================*/

CREATE TABLE DOC.CONSENTIMIENTOS(
    ID_CONSENTIMIENTO INT IDENTITY CONSTRAINT PK_CONSENTIMIENTOS PRIMARY KEY,
    TITULO VARCHAR(200),
    CONTENIDO TEXT,
    ID_ESTADO INT,
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);
GO

CREATE TABLE DOC.CONSENTIMIENTOS_FIRMADOS(
    ID_DOCUMENTO INT IDENTITY CONSTRAINT PK_DOC_FIRMADO PRIMARY KEY,
    ID_CONSENTIMIENTO INT,
    ID_PACIENTE INT,
    ID_CONSULTA INT,
    FIRMA VARBINARY(MAX),
    FECHA_FIRMA DATETIME2 DEFAULT SYSDATETIME(),
    FOREIGN KEY(ID_CONSENTIMIENTO) REFERENCES DOC.CONSENTIMIENTOS(ID_CONSENTIMIENTO),
    FOREIGN KEY(ID_PACIENTE) REFERENCES CLI.PACIENTES(ID_PACIENTE),
    FOREIGN KEY(ID_CONSULTA) REFERENCES CLI.CONSULTAS(ID_CONSULTA)
);
GO

CREATE TABLE DOC.FOTOS_PACIENTE(
    ID_FOTO INT IDENTITY CONSTRAINT PK_FOTOS PRIMARY KEY,
    ID_PACIENTE INT,
    ID_CONSULTA INT,
    RUTA_IMAGEN VARCHAR(300),
    DESCRIPCION VARCHAR(200),
    FECHA_SUBIDA DATETIME2 DEFAULT SYSDATETIME(),
    FOREIGN KEY(ID_PACIENTE) REFERENCES CLI.PACIENTES(ID_PACIENTE),
    FOREIGN KEY(ID_CONSULTA) REFERENCES CLI.CONSULTAS(ID_CONSULTA)
);
GO

/*========================================================
TRIGGERS - GESTIÓN AUTOMÁTICA DE STOCK
========================================================*/

-- 1. Trigger para Movimientos Manuales (Compra, Ajuste)
CREATE OR ALTER TRIGGER INV.TR_ACTUALIZAR_STOCK_MOVIMIENTO
ON INV.MOVIMIENTOS_INVENTARIO
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE P
    SET STOCK = P.STOCK + CASE 
        WHEN I.TIPO_MOVIMIENTO IN ('COMPRA', 'INGRESO') THEN I.CANTIDAD
        WHEN I.TIPO_MOVIMIENTO IN ('AJUSTE_POS') THEN I.CANTIDAD
        WHEN I.TIPO_MOVIMIENTO IN ('AJUSTE_NEG') THEN -I.CANTIDAD
        ELSE 0 END
    FROM INV.PRODUCTOS P
    INNER JOIN INSERTED I ON P.ID_PRODUCTO = I.ID_PRODUCTO;
END;
GO

-- 2. Trigger para Ventas (Actualizado para CUENTA_DETALLE)
CREATE OR ALTER TRIGGER CAJA.TR_ACTUALIZAR_STOCK_POR_CUENTA
ON CAJA.CUENTA_DETALLE
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;
    
    -- Solo descontar si es un PRODUCTO
    UPDATE P
    SET STOCK = P.STOCK - I.CANTIDAD
    FROM INV.PRODUCTOS P
    INNER JOIN INSERTED I ON P.ID_PRODUCTO = I.ID_REFERENCIA
    WHERE I.TIPO_ITEM = 'PRODUCTO';

    -- Registrar movimiento para auditoría
    INSERT INTO INV.MOVIMIENTOS_INVENTARIO (ID_PRODUCTO, TIPO_MOVIMIENTO, CANTIDAD, OBSERVACION)
    SELECT ID_REFERENCIA, 'VENTA', -CANTIDAD, 'Venta vinculada a Cuenta ID: ' + CAST(ID_CUENTA AS VARCHAR)
    FROM INSERTED
    WHERE TIPO_ITEM = 'PRODUCTO';
END;
GO

/*========================================================
PROCEDIMIENTOS ALMACENADOS
========================================================*/

CREATE OR ALTER PROCEDURE ADM.SP_CONVERTIR_POSIBLE_A_PACIENTE
    @IdPosiblePaciente INT,
    @IdCita INT,
    @IdTipoIdentificacion INT,
    @NumIdentificacion VARCHAR(25),
    @IdGenero INT,
    @FechaNacimiento DATE,
    @Email VARCHAR(120) = NULL,
    @Direccion VARCHAR(250) = NULL,
    @ContactoEmergencia VARCHAR(120) = NULL,
    @TelefonoEmergencia VARCHAR(20) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION;
    BEGIN TRY
        DECLARE @NewPersonaId INT;
        DECLARE @NewPacienteId INT;
        DECLARE @PNombre VARCHAR(40), @SNombre VARCHAR(40), @PApellido VARCHAR(40), @SApellido VARCHAR(40), @Tel VARCHAR(20);

        SELECT @PNombre = PRIMER_NOMBRE, @SNombre = SEGUNDO_NOMBRE, 
               @PApellido = PRIMER_APELLIDO, @SApellido = SEGUNDO_APELLIDO,
               @Tel = TELEFONO
        FROM CLI.POSIBLES_PACIENTES WHERE ID_POSIBLE_PACIENTE = @IdPosiblePaciente;

        IF @PNombre IS NULL THROW 50001, 'Posible paciente no encontrado.', 1;

        INSERT INTO ADM.PERSONAS (PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, 
                                 ID_TIPO_IDENTIFICACION, NUM_IDENTIFICACION, ID_GENERO, FECHA_NACIMIENTO, 
                                 EMAIL, TELEFONO, DIRECCION, ID_ESTADO)
        VALUES (@PNombre, @SNombre, @PApellido, @SApellido, @IdTipoIdentificacion, @NumIdentificacion, @IdGenero, @FechaNacimiento, 
                @Email, @Tel, @Direccion, 1);
        
        SET @NewPersonaId = SCOPE_IDENTITY();

        INSERT INTO CLI.PACIENTES (ID_PERSONA, CONTACTO_EMERGENCIA, TELEFONO_EMERGENCIA, ID_ESTADO)
        VALUES (@NewPersonaId, @ContactoEmergencia, @TelefonoEmergencia, 1);
        SET @NewPacienteId = SCOPE_IDENTITY();

        UPDATE CLI.CITAS SET ID_PACIENTE = @NewPacienteId, ID_POSIBLE_PACIENTE = NULL, ID_ESTADO_CITA = 2 WHERE ID_CITA = @IdCita;

        INSERT INTO CLI.ASISTENCIA_CITAS (ID_CITA, ID_TIPO_ASISTENCIA, OBSERVACION)
        VALUES (@IdCita, 2, 'Conversión de prospecto a paciente oficial');

        UPDATE CLI.POSIBLES_PACIENTES SET ID_ESTADO = 2 WHERE ID_POSIBLE_PACIENTE = @IdPosiblePaciente;

        COMMIT;
        SELECT @NewPacienteId AS ID_PACIENTE_GENERADO;
    END TRY
    BEGIN CATCH
        ROLLBACK;
        THROW;
    END CATCH
END;
GO
