/*========================================================
MEDITECH DB v4.0 - Edición Consolidada Final (Incluye Roles Granulares)
Arquitectura profesional: Clínica + Inventario + Caja + Exámenes + Permisos
========================================================*/

USE MediTech;
GO

/*========================================================
1. SCHEMAS
========================================================*/
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'CAT') EXEC('CREATE SCHEMA CAT');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'ADM') EXEC('CREATE SCHEMA ADM');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'CLI') EXEC('CREATE SCHEMA CLI');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'DOC') EXEC('CREATE SCHEMA DOC');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'CAJA') EXEC('CREATE SCHEMA CAJA');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'INV') EXEC('CREATE SCHEMA INV');
GO

/*========================================================
2. CATALOGOS BASE (CAT)
========================================================*/

-- Estados Generales
CREATE TABLE CAT.ESTADOS(
    ID_ESTADO INT IDENTITY(1,1) CONSTRAINT PK_ESTADOS PRIMARY KEY,
    DESC_ESTADO VARCHAR(50) NOT NULL,
    FECHA_CREACION DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

INSERT INTO CAT.ESTADOS (DESC_ESTADO) VALUES 
('ACTIVO'), ('INACTIVO'), ('ANULADO'), ('EN PROCESO'), ('FINALIZADA'), ('CANCELADA');
GO

-- Roles de Usuario
CREATE TABLE CAT.ROLES(
    ID_ROL INT IDENTITY PRIMARY KEY,
    DESC_ROL VARCHAR(80) NOT NULL,
    ID_ESTADO INT NOT NULL DEFAULT 1,
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);

INSERT INTO CAT.ROLES (DESC_ROL) VALUES ('ADMINISTRADOR'), ('DOCTOR'), ('ASISTENTE');
GO

-- Tipos de Identificación
CREATE TABLE CAT.TIPO_IDENTIFICACION(
    ID_TIPO_IDENTIFICACION INT IDENTITY PRIMARY KEY,
    DESC_TIPO VARCHAR(50) NOT NULL,
    ID_ESTADO INT NOT NULL DEFAULT 1,
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);

INSERT INTO CAT.TIPO_IDENTIFICACION (DESC_TIPO) VALUES ('CEDULA'), ('PASAPORTE'), ('RESIDENCIA');
GO

-- Géneros
CREATE TABLE CAT.GENEROS(
    ID_GENERO INT IDENTITY PRIMARY KEY,
    DESC_GENERO VARCHAR(20),
    ID_ESTADO INT NOT NULL DEFAULT 1,
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);

INSERT INTO CAT.GENEROS(DESC_GENERO) VALUES ('MASCULINO'), ('FEMENINO'), ('OTRO');
GO

-- Monedas
CREATE TABLE CAT.MONEDAS(
    ID_MONEDA INT IDENTITY CONSTRAINT PK_MONEDAS PRIMARY KEY,
    CODIGO VARCHAR(10) NOT NULL, -- USD, NIO
    NOMBRE VARCHAR(50) NOT NULL,
    SIMBOLO VARCHAR(5)
);

INSERT INTO CAT.MONEDAS (CODIGO, NOMBRE, SIMBOLO) VALUES ('USD', 'DOLAR', '$'), ('NIO', 'CORDOBA', 'C$');
GO

-- Estado de Citas
CREATE TABLE CAT.ESTADO_CITA(
    ID_ESTADO_CITA INT IDENTITY PRIMARY KEY,
    DESC_ESTADO_CITA VARCHAR(50) NOT NULL,
    ID_ESTADO INT NOT NULL DEFAULT 1
);

INSERT INTO CAT.ESTADO_CITA (DESC_ESTADO_CITA) VALUES 
('PROGRAMADA'), ('EN CURSO'), ('FINALIZADA'), ('CANCELADA'), ('NO ASISTIÓ');
GO

/*========================================================
3. ADMINISTRACIÓN (ADM)
========================================================*/

-- Configuración de Moneda Base
CREATE TABLE ADM.CONFIGURACION_MONEDA(
    ID_CONFIGURACION INT IDENTITY CONSTRAINT PK_CONFIG_MONEDA PRIMARY KEY,
    ID_MONEDA_BASE INT NOT NULL,
    TASA_CAMBIO DECIMAL(12,4) NOT NULL, -- Legacy compat
    FECHA_ACTUALIZACION DATETIME2 DEFAULT SYSDATETIME(),
    USUARIO_MODIFICACION VARCHAR(80),
    FOREIGN KEY(ID_MONEDA_BASE) REFERENCES CAT.MONEDAS(ID_MONEDA)
);

-- Tasas de Cambio Detalladas
CREATE TABLE ADM.TASA_CAMBIO (
    ID_TASA INT IDENTITY CONSTRAINT PK_TASA_CAMBIO PRIMARY KEY,
    ID_MONEDA_ORIGEN INT NOT NULL,
    ID_MONEDA_DESTINO INT NOT NULL,
    VALOR DECIMAL(18,6) NOT NULL,
    FECHA DATETIME2 DEFAULT SYSDATETIME(),
    ACTIVO BIT DEFAULT 1,
    USUARIO_MODIFICACION VARCHAR(80),
    FOREIGN KEY(ID_MONEDA_ORIGEN) REFERENCES CAT.MONEDAS(ID_MONEDA),
    FOREIGN KEY(ID_MONEDA_DESTINO) REFERENCES CAT.MONEDAS(ID_MONEDA)
);
CREATE UNIQUE INDEX UX_TASA_ACTIVA ON ADM.TASA_CAMBIO(ID_MONEDA_ORIGEN, ID_MONEDA_DESTINO) WHERE ACTIVO = 1;
GO

-- Personas (Entidad Base)
CREATE TABLE ADM.PERSONAS(
    ID_PERSONA INT IDENTITY CONSTRAINT PK_PERSONAS PRIMARY KEY,
    PRIMER_NOMBRE VARCHAR(40) NOT NULL,
    SEGUNDO_NOMBRE VARCHAR(40),
    PRIMER_APELLIDO VARCHAR(40) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR(40),
    ID_TIPO_IDENTIFICACION INT NOT NULL,
    NUM_IDENTIFICACION VARCHAR(25) NOT NULL,
    ID_GENERO INT NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    EMAIL VARCHAR(120),
    TELEFONO VARCHAR(20) NOT NULL,
    DIRECCION VARCHAR(250),
    FECHA_CREACION DATETIME2 DEFAULT SYSDATETIME(),
    ID_ESTADO INT NOT NULL DEFAULT 1,
    CONSTRAINT UQ_IDENTIFICACION UNIQUE(ID_TIPO_IDENTIFICACION, NUM_IDENTIFICACION),
    FOREIGN KEY(ID_TIPO_IDENTIFICACION) REFERENCES CAT.TIPO_IDENTIFICACION(ID_TIPO_IDENTIFICACION),
    FOREIGN KEY(ID_GENERO) REFERENCES CAT.GENEROS(ID_GENERO),
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);
GO

-- Empleados
CREATE TABLE ADM.EMPLEADOS(
    ID_EMPLEADO INT IDENTITY CONSTRAINT PK_EMPLEADOS PRIMARY KEY,
    ID_PERSONA INT NOT NULL,
    ID_ROL INT NOT NULL,
    FECHA_CONTRATACION DATE,
    ID_ESTADO INT DEFAULT 1,
    FOREIGN KEY(ID_PERSONA) REFERENCES ADM.PERSONAS(ID_PERSONA),
    FOREIGN KEY(ID_ROL) REFERENCES CAT.ROLES(ID_ROL)
);
GO

-- Usuarios (Acceso al Sistema)
CREATE TABLE ADM.USUARIOS(
    ID_USUARIO INT IDENTITY CONSTRAINT PK_USUARIOS PRIMARY KEY,
    USERNAME VARCHAR(80) NOT NULL UNIQUE,
    PASSWORD_HASH VARBINARY(MAX),
    PASSWORD_SALT VARBINARY(MAX),
    ID_EMPLEADO INT,
    ID_ROL INT,
    FECHA_CREACION DATETIME2 DEFAULT SYSDATETIME(),
    ID_ESTADO INT,
    FOREIGN KEY(ID_EMPLEADO) REFERENCES ADM.EMPLEADOS(ID_EMPLEADO),
    FOREIGN KEY(ID_ROL) REFERENCES CAT.ROLES(ID_ROL)
);
GO

-- Módulos del Sistema
CREATE TABLE ADM.MODULOS (
    ID_MODULO INT IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    ICONO VARCHAR(50), -- FontAwesome class
    CONTROLLER VARCHAR(100) NOT NULL, -- Nombre del controlador sin 'Controller'
    ORDEN INT DEFAULT 0,
    ID_ESTADO INT DEFAULT 1,
    FOREIGN KEY (ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);
GO

-- Relación Usuario-Módulos (Permisos Granulares)
CREATE TABLE ADM.USUARIO_MODULOS (
    ID_USUARIO INT NOT NULL,
    ID_MODULO INT NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_MODULO),
    FOREIGN KEY (ID_USUARIO) REFERENCES ADM.USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_MODULO) REFERENCES ADM.MODULOS(ID_MODULO)
);
GO

/*========================================================
4. CLÍNICA (CLI)
========================================================*/

-- Tratamientos (Catálogo)
CREATE TABLE CAT.TRATAMIENTOS(
    ID_TRATAMIENTO INT IDENTITY CONSTRAINT PK_TRATAMIENTOS PRIMARY KEY,
    NOMBRE_TRATAMIENTO VARCHAR(200) NOT NULL,
    PRECIO DECIMAL(12,2),
    DOSIS VARCHAR(100) NULL,
    VIA_ADMINISTRACION VARCHAR(100) NULL,
    FRECUENCIA VARCHAR(100) NULL,
    DURACION_TRATAMIENTO VARCHAR(100) NULL,
    ID_ESTADO INT DEFAULT 1,
    FECHA_ACTUALIZACION DATETIME2 NULL,
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);
GO

-- Pacientes Oficiales
CREATE TABLE CLI.PACIENTES(
    ID_PACIENTE INT IDENTITY CONSTRAINT PK_PACIENTES PRIMARY KEY,
    ID_PERSONA INT NOT NULL,
    OCUPACION VARCHAR(100),
    CONTACTO_EMERGENCIA VARCHAR(120),
    TELEFONO_EMERGENCIA VARCHAR(20),
    FECHA_REGISTRO DATETIME2 DEFAULT SYSDATETIME(),
    ID_ESTADO INT DEFAULT 1,
    FOREIGN KEY(ID_PERSONA) REFERENCES ADM.PERSONAS(ID_PERSONA)
);
GO

-- Posibles Pacientes (Prospectos)
CREATE TABLE CLI.POSIBLES_PACIENTES(
    ID_POSIBLE_PACIENTE INT IDENTITY CONSTRAINT PK_POSIBLE_PACIENTE PRIMARY KEY,
    PRIMER_NOMBRE VARCHAR(40) NOT NULL,
    SEGUNDO_NOMBRE VARCHAR(40),
    PRIMER_APELLIDO VARCHAR(40) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR(40),
    TELEFONO VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME2 DEFAULT SYSDATETIME(),
    ID_ESTADO INT DEFAULT 1
);
GO

-- Citas Médicas
CREATE TABLE CLI.CITAS(
    ID_CITA INT IDENTITY CONSTRAINT PK_CITAS PRIMARY KEY,
    ID_PACIENTE INT NULL, 
    ID_POSIBLE_PACIENTE INT NULL, 
    TELEFONO VARCHAR(20) NOT NULL DEFAULT '00000000',
    ID_TRATAMIENTO INT,
    ID_ESTADO_CITA INT NOT NULL DEFAULT 1,
    FECHA DATE NOT NULL,
    HORA_INICIO TIME NOT NULL,
    HORA_FIN TIME NOT NULL,
    OBSERVACIONES VARCHAR(300),
    FECHA_CREACION DATETIME2 DEFAULT SYSDATETIME(),
    ID_ESTADO INT DEFAULT 1,
    FOREIGN KEY(ID_PACIENTE) REFERENCES CLI.PACIENTES(ID_PACIENTE),
    FOREIGN KEY(ID_POSIBLE_PACIENTE) REFERENCES CLI.POSIBLES_PACIENTES(ID_POSIBLE_PACIENTE),
    FOREIGN KEY(ID_TRATAMIENTO) REFERENCES CAT.TRATAMIENTOS(ID_TRATAMIENTO),
    FOREIGN KEY(ID_ESTADO_CITA) REFERENCES CAT.ESTADO_CITA(ID_ESTADO_CITA)
);
CREATE UNIQUE INDEX UX_CITAS_PACIENTE_HORA ON CLI.CITAS(ID_PACIENTE, FECHA, HORA_INICIO) WHERE ID_PACIENTE IS NOT NULL;
GO

-- Consultas Médicas
CREATE TABLE CLI.CONSULTAS(
    ID_CONSULTA INT IDENTITY CONSTRAINT PK_CONSULTAS PRIMARY KEY,
    ID_CITA INT NOT NULL,
    ID_MEDICO INT NOT NULL,
    MOTIVO_CONSULTA VARCHAR(300),
    DIAGNOSTICO_PRINCIPAL VARCHAR(500),
    OBSERVACIONES VARCHAR(500),
    FECHA_CONSULTA DATETIME2 DEFAULT SYSDATETIME(),
    ID_ESTADO INT DEFAULT 1,
    FOREIGN KEY(ID_CITA) REFERENCES CLI.CITAS(ID_CITA),
    FOREIGN KEY(ID_MEDICO) REFERENCES ADM.EMPLEADOS(ID_EMPLEADO)
);
GO

-- Detalle de Consulta (Tratamientos/Productos usados)
CREATE TABLE CLI.CONSULTA_DETALLE (
    ID_DETALLE_CONSULTA INT IDENTITY CONSTRAINT PK_CONSULTA_DETALLE PRIMARY KEY,
    ID_CONSULTA INT NOT NULL,
    TIPO_ITEM VARCHAR(20), -- TRATAMIENTO/PRODUCTO
    ID_REFERENCIA INT,
    DESCRIPCION NVARCHAR(200),
    CANTIDAD INT,
    PRECIO_UNITARIO DECIMAL(12,2),
    SUBTOTAL DECIMAL(12,2),
    FOREIGN KEY(ID_CONSULTA) REFERENCES CLI.CONSULTAS(ID_CONSULTA)
);
GO

-- Exámenes Clínicos
CREATE TABLE CLI.EXAMENES (
    ID_EXAMEN INT IDENTITY CONSTRAINT PK_EXAMENES PRIMARY KEY,
    ID_PACIENTE INT NOT NULL,
    ID_CONSULTA INT NULL,
    NOMBRE_EXAMEN NVARCHAR(200) NOT NULL,
    FECHA_ORDEN DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    FECHA_RESULTADO DATETIME2 NULL,
    IMAGEN_RESULTADO VARBINARY(MAX) NULL,
    CONTENT_TYPE NVARCHAR(50) NULL,
    COMENTARIO_MEDICO NVARCHAR(MAX) NULL,
    ID_ESTADO INT NOT NULL DEFAULT 1,
    FOREIGN KEY(ID_PACIENTE) REFERENCES CLI.PACIENTES(ID_PACIENTE),
    FOREIGN KEY(ID_CONSULTA) REFERENCES CLI.CONSULTAS(ID_CONSULTA),
    FOREIGN KEY(ID_ESTADO) REFERENCES CAT.ESTADOS(ID_ESTADO)
);
GO

-- Diagnósticos Adicionales
CREATE TABLE CLI.DIAGNOSTICOS(
    ID_DIAGNOSTICO INT IDENTITY CONSTRAINT PK_DIAGNOSTICOS PRIMARY KEY,
    ID_CONSULTA INT NOT NULL,
    DESCRIPCION VARCHAR(250) NOT NULL,
    NOTAS VARCHAR(MAX) NULL,
    FECHA_REGISTRO DATETIME2 DEFAULT SYSDATETIME(),
    ID_ESTADO INT NOT NULL DEFAULT 1,
    FOREIGN KEY(ID_CONSULTA) REFERENCES CLI.CONSULTAS(ID_CONSULTA)
);
GO

-- Signos Vitales
CREATE TABLE CLI.SIGNOS_VITALES(
    ID_SIGNOS INT IDENTITY CONSTRAINT PK_SIGNOS PRIMARY KEY,
    ID_CONSULTA INT UNIQUE, -- UNIQUE INDEX POR ID_CONSULTA
    PRESION_ARTERIAL VARCHAR(15),
    TEMPERATURA DECIMAL(5,2),
    FRECUENCIA_CARDIACA INT,
    SATURACION_OXIGENO INT,
    PESO DECIMAL(5,2),
    ALTURA DECIMAL(5,2),
    FOREIGN KEY(ID_CONSULTA) REFERENCES CLI.CONSULTAS(ID_CONSULTA)
);
GO

-- Historial Clínico Integral
CREATE TABLE CLI.HISTORIAL_CLINICO (
    ID_HISTORIAL INT IDENTITY CONSTRAINT PK_HISTORIAL PRIMARY KEY,
    ID_PACIENTE INT NOT NULL,
    ALERGIAS BIT NOT NULL DEFAULT 0,
    ALERGIAS_DETALLE VARCHAR(500),
    DIABETES BIT NOT NULL DEFAULT 0,
    TOMA_MEDICAMENTO BIT NOT NULL DEFAULT 0,
    MEDICAMENTO_DETALLE VARCHAR(500),
    HIPERTENSION BIT NOT NULL DEFAULT 0,
    EMBARAZADA BIT NOT NULL DEFAULT 0,
    CARDIACOS BIT NOT NULL DEFAULT 0,
    ANTECEDENTE_ONCOLOGICO BIT NOT NULL DEFAULT 0,
    OTROS_PADECIMIENTOS BIT NOT NULL DEFAULT 0,
    OTROS_PADECIMIENTOS_DETALLE VARCHAR(500),
    CONSUME_ALCOHOL BIT NOT NULL DEFAULT 0,
    FUMA_CIGARRILLOS BIT NOT NULL DEFAULT 0,
    REALIZA_EJERCICIO BIT NOT NULL DEFAULT 0,
    CIRUGIAS_ESTETICAS BIT NOT NULL DEFAULT 0,
    CIRUGIAS_ESTETICAS_DETALLE VARCHAR(500),
    FECHA_REGISTRO DATETIME2 DEFAULT SYSDATETIME(),
    FECHA_ACTUALIZACION DATETIME2,
    FOREIGN KEY(ID_PACIENTE) REFERENCES CLI.PACIENTES(ID_PACIENTE)
);
GO

/*========================================================
5. INVENTARIO (INV)
========================================================*/

-- Productos
CREATE TABLE INV.PRODUCTOS(
    ID_PRODUCTO INT IDENTITY CONSTRAINT PK_PRODUCTOS PRIMARY KEY,
    NOMBRE VARCHAR(120) NOT NULL,
    DESCRIPCION VARCHAR(300),
    PRECIO DECIMAL(12,2),
    STOCK INT DEFAULT 0,
    STOCK_MINIMO INT DEFAULT 0,
    ACTIVO BIT DEFAULT 1,
    FECHA_CREACION DATETIME2 DEFAULT SYSDATETIME(),
    CONSTRAINT CHK_PRODUCTO_STOCK_POSITIVO CHECK (STOCK >= 0)
);
GO

-- Movimientos de Inventario
CREATE TABLE INV.MOVIMIENTOS_INVENTARIO(
    ID_MOVIMIENTO INT IDENTITY CONSTRAINT PK_MOVIMIENTO PRIMARY KEY,
    ID_PRODUCTO INT NOT NULL,
    TIPO_MOVIMIENTO VARCHAR(20), -- COMPRA, VENTA, AJUSTE
    CANTIDAD INT,
    FECHA_MOVIMIENTO DATETIME2 DEFAULT SYSDATETIME(),
    OBSERVACION VARCHAR(200),
    FOREIGN KEY(ID_PRODUCTO) REFERENCES INV.PRODUCTOS(ID_PRODUCTO)
);
GO

/*========================================================
6. FINANZAS (CAJA)
========================================================*/

-- Cuentas por Cobrar
CREATE TABLE CAJA.CUENTAS(
    ID_CUENTA INT IDENTITY CONSTRAINT PK_CUENTAS PRIMARY KEY,
    ID_PACIENTE INT,
    ID_CONSULTA INT,
    TOTAL_BRUTO DECIMAL(12,2),
    DESCUENTO DECIMAL(12,2) DEFAULT 0,
    TOTAL_FINAL DECIMAL(12,2),
    ID_MONEDA_BASE INT,
    FECHA_CREACION DATETIME2 DEFAULT SYSDATETIME(),
    FOREIGN KEY(ID_PACIENTE) REFERENCES CLI.PACIENTES(ID_PACIENTE),
    FOREIGN KEY(ID_CONSULTA) REFERENCES CLI.CONSULTAS(ID_CONSULTA),
    FOREIGN KEY(ID_MONEDA_BASE) REFERENCES CAT.MONEDAS(ID_MONEDA)
);
GO

-- Detalles de la Cuenta
CREATE TABLE CAJA.CUENTA_DETALLE(
    ID_DETALLE INT IDENTITY CONSTRAINT PK_CUENTA_DETALLE PRIMARY KEY,
    ID_CUENTA INT NOT NULL,
    TIPO_ITEM VARCHAR(20), -- TRATAMIENTO / PRODUCTO
    ID_REFERENCIA INT,
    DESCRIPCION VARCHAR(200),
    CANTIDAD INT,
    PRECIO_UNITARIO DECIMAL(12,2),
    SUBTOTAL DECIMAL(12,2),
    FOREIGN KEY(ID_CUENTA) REFERENCES CAJA.CUENTAS(ID_CUENTA)
);
GO

-- Registro de Pagos
CREATE TABLE CAJA.PAGOS(
    ID_PAGO INT IDENTITY CONSTRAINT PK_PAGOS PRIMARY KEY,
    ID_CUENTA INT NOT NULL,
    MONTO DECIMAL(12,2), -- Monto pagado en la moneda seleccionada
    MONTO_BASE DECIMAL(12,2), -- Monto equivalente en moneda base (USD)
    ID_MONEDA INT,
    METODO_PAGO VARCHAR(30), -- EFECTIVO, TARJETA, TRANSFERENCIA
    TASA_CAMBIO_APLICADA DECIMAL(18,6),
    FECHA_PAGO DATETIME2 DEFAULT SYSDATETIME(),
    FOREIGN KEY(ID_CUENTA) REFERENCES CAJA.CUENTAS(ID_CUENTA),
    FOREIGN KEY(ID_MONEDA) REFERENCES CAT.MONEDAS(ID_MONEDA)
);
GO

/*========================================================
7. GESTIÓN DE DOCUMENTOS (DOC)
========================================================*/

-- Archivos Clínicos y Archivos Adjuntos
CREATE TABLE DOC.DOCUMENTOS_CLINICOS (
    ID_DOCUMENTO INT IDENTITY CONSTRAINT PK_DOCUMENTOS_CLINICOS PRIMARY KEY,
    ID_PACIENTE INT NOT NULL,
    NOMBRE_ARCHIVO NVARCHAR(200) NOT NULL,
    TITULO NVARCHAR(200),
    CONTENIDO VARBINARY(MAX) NOT NULL,
    CONTENT_TYPE NVARCHAR(100) NOT NULL,
    TAMANO_BYTES BIGINT NOT NULL DEFAULT 0,
    FECHA_REGISTRO DATETIME2 DEFAULT SYSDATETIME(),
    FOREIGN KEY(ID_PACIENTE) REFERENCES CLI.PACIENTES(ID_PACIENTE)
);
GO

-- Galería de Fotos Clínicas
CREATE TABLE CLI.FOTOS_CLINICAS (
    ID_FOTO INT IDENTITY CONSTRAINT PK_FOTOS_CLINICAS PRIMARY KEY,
    ID_PACIENTE INT NOT NULL,
    TITULO NVARCHAR(200),
    CONTENIDO VARBINARY(MAX) NOT NULL,
    CONTENT_TYPE NVARCHAR(50) NOT NULL,
    FECHA_REGISTRO DATETIME2 DEFAULT SYSDATETIME(),
    FOREIGN KEY(ID_PACIENTE) REFERENCES CLI.PACIENTES(ID_PACIENTE)
);
GO

/*========================================================
8. PROCEDIMIENTOS ALMACENADOS
========================================================*/

-- Conversión Automática de Prospecto a Paciente
CREATE OR ALTER PROCEDURE ADM.SP_CONVERTIR_POSIBLE_A_PACIENTE
    @IdPosiblePaciente INT,
    @IdCita INT,
    @IdTipoIdentificacion INT,
    @NumIdentificacion VARCHAR(25),
    @IdGenero INT,
    @FechaNacimiento DATE,
    @Email VARCHAR(120) = NULL,
    @Direccion VARCHAR(250) = NULL,
    @ContactoEmergencia VARCHAR(120) = NULL,
    @TelefonoEmergencia VARCHAR(20) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION;
    BEGIN TRY
        DECLARE @NewPersonaId INT;
        DECLARE @NewPacienteId INT;
        DECLARE @PNombre VARCHAR(40), @SNombre VARCHAR(40), @PApellido VARCHAR(40), @SApellido VARCHAR(40), @Tel VARCHAR(20);

        SELECT @PNombre = PRIMER_NOMBRE, @SNombre = SEGUNDO_NOMBRE, 
               @PApellido = PRIMER_APELLIDO, @SApellido = SEGUNDO_APELLIDO,
               @Tel = TELEFONO
        FROM CLI.POSIBLES_PACIENTES WHERE ID_POSIBLE_PACIENTE = @IdPosiblePaciente;

        IF @PNombre IS NULL THROW 50001, 'Posible paciente no encontrado.', 1;

        -- Buscar si la persona ya existe por su identificación
        SELECT @NewPersonaId = ID_PERSONA FROM ADM.PERSONAS WHERE NUM_IDENTIFICACION = @NumIdentificacion;

        IF @NewPersonaId IS NULL
        BEGIN
            INSERT INTO ADM.PERSONAS (PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, 
                                     ID_TIPO_IDENTIFICACION, NUM_IDENTIFICACION, ID_GENERO, FECHA_NACIMIENTO, 
                                     EMAIL, TELEFONO, DIRECCION, ID_ESTADO)
            VALUES (@PNombre, @SNombre, @PApellido, @SApellido, @IdTipoIdentificacion, @NumIdentificacion, @IdGenero, @FechaNacimiento, 
                    @Email, @Tel, @Direccion, 1);
            
            SET @NewPersonaId = SCOPE_IDENTITY();
        END

        -- Verificar si ya es paciente
        SELECT @NewPacienteId = ID_PACIENTE FROM CLI.PACIENTES WHERE ID_PERSONA = @NewPersonaId;

        IF @NewPacienteId IS NULL
        BEGIN
            INSERT INTO CLI.PACIENTES (ID_PERSONA, CONTACTO_EMERGENCIA, TELEFONO_EMERGENCIA, ID_ESTADO)
            VALUES (@NewPersonaId, @ContactoEmergencia, @TelefonoEmergencia, 1);
            SET @NewPacienteId = SCOPE_IDENTITY();
        END

        -- Actualizar Cita
        UPDATE CLI.CITAS SET ID_PACIENTE = @NewPacienteId, ID_POSIBLE_PACIENTE = NULL, ID_ESTADO_CITA = 2 WHERE ID_CITA = @IdCita;

        -- Marcar prospecto como gestionado
        UPDATE CLI.POSIBLES_PACIENTES SET ID_ESTADO = 2 WHERE ID_POSIBLE_PACIENTE = @IdPosiblePaciente;

        COMMIT;
        SELECT @NewPacienteId AS ID_PACIENTE_GENERADO;
    END TRY
    BEGIN CATCH
        ROLLBACK;
        THROW;
    END CATCH
END;
GO

/*========================================================
9. TRIGGERS (STOCK AUTOMÁTICO)
========================================================*/

-- Sincronización de Stock por Movimientos Manuales
CREATE OR ALTER TRIGGER INV.TR_ACTUALIZAR_STOCK_MOVIMIENTO
ON INV.MOVIMIENTOS_INVENTARIO
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE P
    SET STOCK = P.STOCK + CASE 
        WHEN I.TIPO_MOVIMIENTO IN ('COMPRA', 'INGRESO', 'AJUSTE_POS') THEN I.CANTIDAD
        WHEN I.TIPO_MOVIMIENTO IN ('AJUSTE_NEG') THEN -I.CANTIDAD
        ELSE 0 END
    FROM INV.PRODUCTOS P
    INNER JOIN INSERTED I ON P.ID_PRODUCTO = I.ID_PRODUCTO;
END;
GO

-- Descuento de Stock por Ventas
CREATE OR ALTER TRIGGER CAJA.TR_ACTUALIZAR_STOCK_POR_CUENTA
ON CAJA.CUENTA_DETALLE
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;
    
    UPDATE P
    SET STOCK = P.STOCK - I.CANTIDAD
    FROM INV.PRODUCTOS P
    INNER JOIN INSERTED I ON P.ID_PRODUCTO = I.ID_REFERENCIA
    WHERE I.TIPO_ITEM = 'PRODUCTO';

    -- Registrar movimiento para auditoría
    INSERT INTO INV.MOVIMIENTOS_INVENTARIO (ID_PRODUCTO, TIPO_MOVIMIENTO, CANTIDAD, OBSERVACION)
    SELECT ID_REFERENCIA, 'VENTA', -CANTIDAD, 'Venta automática - Cuenta ID: ' + CAST(ID_CUENTA AS VARCHAR)
    FROM INSERTED
    WHERE TIPO_ITEM = 'PRODUCTO';
END;
GO

/*========================================================
10. SEMILLAS (INITIAL DATA)
========================================================*/

-- Tasa de Cambio Base
INSERT INTO ADM.TASA_CAMBIO (ID_MONEDA_ORIGEN, ID_MONEDA_DESTINO, VALOR, USUARIO_MODIFICACION)
VALUES (1, 2, 36.621500, 'SISTEMA');

INSERT INTO ADM.CONFIGURACION_MONEDA (ID_MONEDA_BASE, TASA_CAMBIO, USUARIO_MODIFICACION)
VALUES (1, 36.6215, 'SISTEMA');
GO

-- Tratamientos Base
INSERT INTO CAT.TRATAMIENTOS (NOMBRE_TRATAMIENTO, PRECIO) VALUES 
('CONSULTA GENERAL', 40), 
('LIMPIEZA DENTAL', 50), 
('EXTRACCION SIMPLE', 45), 
('ORTODONCIA - CONTROL', 35);
GO

-- Módulos Base
SET IDENTITY_INSERT ADM.MODULOS ON;
INSERT INTO ADM.MODULOS (ID_MODULO, NOMBRE, ICONO, CONTROLLER, ORDEN) VALUES
(1, 'Dashboard', 'fas fa-th-large', 'Home', 1),
(2, 'Citas', 'fas fa-calendar-alt', 'Citas', 2),
(3, 'Pacientes', 'fas fa-user-injured', 'Pacientes', 3),
(4, 'Tratamientos', 'fas fa-hand-holding-medical', 'Tratamientos', 4),
(5, 'Consultas', 'fas fa-stethoscope', 'Consultas', 5),
(6, 'Inventario', 'fas fa-boxes', 'Inventario', 6),
(7, 'Caja y Pagos', 'fas fa-cash-register', 'Caja', 7),
(8, 'Exámenes', 'fas fa-microscope', 'Examenes', 8),
(9, 'Configuración', 'fas fa-cog', 'Configuracion', 9);
SET IDENTITY_INSERT ADM.MODULOS OFF;
GO

-- Asignación inicial de módulos al administrador (ID_ROL = 1)
INSERT INTO ADM.USUARIO_MODULOS (ID_USUARIO, ID_MODULO)
SELECT U.ID_USUARIO, M.ID_MODULO
FROM ADM.USUARIOS U
CROSS JOIN ADM.MODULOS M
WHERE U.ID_ROL = 1;
GO
